# .github/workflows/ci.yml
name: ci

on: [push, pull_request]

jobs:
  ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    with:
      disable_phpcpd: true
      disable_master: true
    secrets:
      moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}